name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build JAR
        run: ./mvnw package --file pom.xml

      - name: Build Docker image
        run: docker build -t dasunkad/library-manager-core:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dasunkad
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image
        run: docker push dasunkad/library-manager-core:latest
